env:
  node: true
  es2021: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  quotes: ['error', 'single'],
  no-mixed-spaces-and-tabs: 'error',
  no-unused-vars: 'error',
  no-multi-spaces: ['error'],
  no-console: 0,
  import/extensions: 0
}
